---
title: "HW 9"
author: "Cassandra"
date: "4/5/2018"
output: html_document
---

```{r setup, include=FALSE}
docapt <- read.csv("KaggleV2-May-2016.csv")
library(chron)
library(lubridate)
library(ggplot2)
```

```{r}
docapt$PatientId <- NULL
docapt$AppointmentID <- NULL

docapt$fullScheduledDate <- as.POSIXct(substr(docapt$ScheduledDay, 1, 10))
docapt$fullScheduledTime <- as.POSIXct(substr(docapt$ScheduledDay, 12, 19), format = "%H:%M:%OS")
docapt$AppointmentDay <- as.POSIXct(substr(docapt$AppointmentDay, 1, 10))

docapt$ScheduledDay <- NULL

docapt$No.show <- ifelse(docapt$No.show == "No", 1, 0)
#1 = showed up, 0 = no show

docapt$hourOfSchedule <- hour(docapt$fullScheduledTime) #helps with time of day
docapt$hourOfSchedule <- ifelse((minute(docapt$fullScheduledTime) >= 16 & minute(docapt$fullScheduledTime) <= 30), docapt$hourOfSchedule+0.25, docapt$hourOfSchedule)
docapt$hourOfSchedule <- ifelse((minute(docapt$fullScheduledTime) >= 31 & minute(docapt$fullScheduledTime) <= 45), docapt$hourOfSchedule+0.5, docapt$hourOfSchedule)
docapt$hourOfSchedule <- ifelse((minute(docapt$fullScheduledTime) >= 46 & minute(docapt$fullScheduledTime) <= 60), docapt$hourOfSchedule+0.75, docapt$hourOfSchedule)

patientHours <- seq(from = 0, to = 23.75, by = 0.25)
numPatientHoursAt <- numeric(length(patientHours))
for(i in 1:length(patientHours)) {
  numPatientHoursAt[i] = length(which(docapt$hourOfSchedule == patientHours[i])) 
}

patientHours$numHours <- as.data.frame(patientHours)
numPatientHoursAt <- as.data.frame(numPatientHoursAt)
docapt1 <- cbind(patientHours, numPatientHoursAt)

#this plot shows how many patients are scheduling appointments per each 15 minute interval in the day
scheduledTimePlot <- ggplot(data = docapt1, aes(x=patientHours, y=numPatientHoursAt)) + geom_line() + geom_smooth()
scheduledTimePlot
```

```{r}
docapt$weekday <- weekdays(as.Date(docapt$fullScheduledDate))
docapt$month <- format(docapt$fullScheduledDate,"%m")
docapt$month <- as.numeric(as.character(docapt$month))
docapt$weekday <- ordered(docapt$weekday, levels = c("Sunday","Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))

barplot(table(docapt$weekday), ylab = "Number of Scheduled Appointments", xlab ="Day", main="Number of Patients Scheduling Appointments per Day of Week", col = c("Red","Orange","Blue","Green","Purple"))

counts= table(docapt$No.show, docapt$weekday)
barplot(counts, main="Appointment Data by Day of Week", beside=TRUE, names.arg = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), legend = c("No Show", "Show"), col = c("Green","Blue"), xlab = "Number of Appointments", ylab= "Number of People")

monProp <- length(which(docapt$weekday == "Monday" & docapt$No.show == 0)) / (length(which(docapt$weekday == "Monday" & docapt$No.show == 0)) + length(which(docapt$weekday == "Monday" & docapt$No.show == 1)))

tuesProp <- length(which(docapt$weekday == "Tuesday" & docapt$No.show == 0)) / (length(which(docapt$weekday == "Tuesday" & docapt$No.show == 0)) + length(which(docapt$weekday == "Tuesday" & docapt$No.show == 1)))

wedProp <- length(which(docapt$weekday == "Wednesday" & docapt$No.show == 0)) / (length(which(docapt$weekday == "Wednesday" & docapt$No.show == 0)) + length(which(docapt$weekday == "Wednesday" & docapt$No.show == 1)))

thursProp <- length(which(docapt$weekday == "Thursday" & docapt$No.show == 0)) / (length(which(docapt$weekday == "Thursday" & docapt$No.show == 0)) + length(which(docapt$weekday == "Thursday" & docapt$No.show == 1)))

friProp <- length(which(docapt$weekday == "Friday" & docapt$No.show == 0)) / (length(which(docapt$weekday == "Friday" & docapt$No.show == 0)) + length(which(docapt$weekday == "Friday" & docapt$No.show == 1)))

cat("The proportion of no shows per each day of the week are as follows. Monday:", monProp, ". Tuesday:", tuesProp, ". Wednesday:", wedProp, ". Thursday:", thursProp, ". Friday:", friProp, ". As we can see, the proportion of no shows were the highest on Fridays.")
```

```{r}
barplot(table(docapt$month), ylab = "Number of Scheduled Appointments", xlab ="Day", main="Number of Patients Scheduling Appointments per Month", col = docapt$month)

counts2= table(docapt$No.show, docapt$month)
barplot(counts2, main="Appointment Data by Month", beside=TRUE, legend = c("No Show", "Show"), xlab = "Number of Appointments", ylab= "Number of People", col = c("Green","Blue"))

janProp <- length(which(docapt$month == 1 & docapt$No.show == 0)) / (length(which(docapt$month == 1 & docapt$No.show == 0)) + length(which(docapt$month == 1 & docapt$No.show == 1)))

febProp <- length(which(docapt$month == 2 & docapt$No.show == 0)) / (length(which(docapt$month == 2 & docapt$No.show == 0)) + length(which(docapt$month == 2 & docapt$No.show == 1)))

marProp <- length(which(docapt$month == 3 & docapt$No.show == 0)) / (length(which(docapt$month == 3 & docapt$No.show == 0)) + length(which(docapt$month == 3 & docapt$No.show == 1)))

aprProp <- length(which(docapt$month == 4 & docapt$No.show == 0)) / (length(which(docapt$month == 4 & docapt$No.show == 0)) + length(which(docapt$month == 4 & docapt$No.show == 1)))

mayProp <- length(which(docapt$month == 5 & docapt$No.show == 0)) / (length(which(docapt$month == 5 & docapt$No.show == 0)) + length(which(docapt$month == 5 & docapt$No.show == 1)))

juneProp <- length(which(docapt$month == 6 & docapt$No.show == 0)) / (length(which(docapt$month == 6 & docapt$No.show == 0)) + length(which(docapt$month == 6 & docapt$No.show == 1)))

novProp <- length(which(docapt$month == 11 & docapt$No.show == 0)) / (length(which(docapt$month == 11 & docapt$No.show == 0)) + length(which(docapt$month == 11 & docapt$No.show == 1)))

decProp <- length(which(docapt$month == 12 & docapt$No.show == 0)) / (length(which(docapt$month == 12 & docapt$No.show == 0)) + length(which(docapt$month == 12 & docapt$No.show == 1)))

cat("The proportion of no shows per each month of scheduling are as follows. January:", janProp, ". February:", febProp, ". March:", marProp, ". April:", aprProp, ". May:", mayProp, ". June:", juneProp, ". November:", novProp, ". December:", decProp, ". As we can see, the proportion of no shows were the highest when the appointment were scheduled in March. However, we believe that this may be because the dataset does not show us many appointments made during most months available, so this potentially may be skewed, and would thus not be the best indicator of whether a patient would be a no-show appointment or not.")
```

```{r}
docapt$appointmentMonth <- format(docapt$AppointmentDay,"%m")
docapt$appointmentMonth <- as.numeric(as.character(docapt$appointmentMonth), na.rm=TRUE)
barplot(table(docapt$appointmentMonth), ylab = "Number of Scheduled Appointments", xlab ="Month", main="Number of Patients Scheduled Appointments per Month", col = docapt$appointmentMonth)

counts3= table(docapt$No.show, month(docapt$appointmentMonth))
barplot(counts3, main="Scheduled Appointment Data by Month", beside=TRUE, legend = c("No Show", "Show"), xlab = "Number of Appointments", ylab= "Number of People", col = c("Green","Blue"))

aprProp <- length(which(docapt$appointmentMonth == 4 & docapt$No.show == 0)) / (length(which(docapt$appointmentMonth == 4 & docapt$No.show == 0)) + length(which(docapt$appointmentMonth == 4 & docapt$No.show == 1)))

mayProp <- length(which(docapt$appointmentMonth == 5 & docapt$No.show == 0)) / (length(which(docapt$appointmentMonth == 5 & docapt$No.show == 0)) + length(which(docapt$appointmentMonth == 5 & docapt$No.show == 1)))

juneProp <- length(which(docapt$appointmentMonth == 6 & docapt$No.show == 0)) / (length(which(docapt$appointmentMonth == 6 & docapt$No.show == 0)) + length(which(docapt$appointmentMonth == 6 & docapt$No.show == 1)))

cat("The proportion of no shows per each month where appointments were made are as follows. April:", aprProp, ". May:", mayProp, ". June:", juneProp, ". As we can see, the proportion of no shows were the highest in May. However, like said above, the dataset does not show us many appointments made during other months, so this may potentially be skewed, and would thus not be the best indicator of whether a patient would be a no-show appointment or not.")
```

```{r}
docapt$waitingTime <- docapt$AppointmentDay - docapt$fullScheduledDate
#gets the number of days instead of seconds
docapt$waitingTime <- (docapt$waitingTime / 86400)

plot1 <- ggplot() + geom_jitter(aes(y = docapt$waitingTime, x = docapt$No.show), data = docapt, stat="identity")
plot1

proportionNoShows = length(which(docapt$No.show == 0)) / (length(which(docapt$No.show == 1)) + length(which(docapt$No.show == 0)))

cat("The number of patients showing up to the appointment is", length(which(docapt$No.show == 1)), "and the number of docapt not showing up to the appointment is", length(which(docapt$No.show == 0)), ". The proportion of people not showing up is", proportionNoShows, ".")

prop50 <- length(which(docapt$No.show == 0 & docapt$waitingTime >= 0 & docapt$waitingTime < 50)) / (length(which(docapt$No.show == 1 & docapt$waitingTime >= 0 & docapt$waitingTime < 50)) + length(which(docapt$No.show == 0 & docapt$waitingTime >= 0 & docapt$waitingTime < 50)))

prop100 <- length(which(docapt$No.show == 0 & docapt$waitingTime >= 50 & docapt$waitingTime < 100)) / (length(which(docapt$No.show == 1 & docapt$waitingTime >= 50 & docapt$waitingTime < 100)) + length(which(docapt$No.show == 0 & docapt$waitingTime >= 50 & docapt$waitingTime < 100)))

prop150 <- length(which(docapt$No.show == 0 & docapt$waitingTime >= 100 & docapt$waitingTime < 150)) / (length(which(docapt$No.show == 1 & docapt$waitingTime >= 100 & docapt$waitingTime < 150)) + length(which(docapt$No.show == 0 & docapt$waitingTime >= 100 & docapt$waitingTime < 150)))

propOver <- length(which(docapt$No.show == 0 & docapt$waitingTime >= 150)) / (length(which(docapt$No.show == 1 & docapt$waitingTime >= 150)) + length(which(docapt$No.show == 0 & docapt$waitingTime >= 150)))

cat("The proportion of patients who waited between 0 and 50 days for their doctor appointment and did not show up is", prop50, ". The proportion of patients who waited between 50 and 100 days for their doctor appointment and did not show up is", prop100, ". The proportion of patients who waited between 100 and 150 days for their doctor appointment and did not show up is", prop150, ". Finally, the proportion of patients who waited over 150 days for their doctor appointment and did not show up is", propOver, ". This information is interesting because it seems like the proportion of no-shows tend to increase as the waiting time between scheduling the doctor appointment, which indicates that people may have forgotten that they had scheduled an appointment and thus did not show up, or there may be another underlying reason why they did not show up. This will be explored in the rest of our code.")
```

```{r}
lmModelSicknesses <- lm(No.show ~ Hipertension + Diabetes + Alcoholism + Handcap, data = docapt)
summary(lmModelSicknesses)

cat("This linear regression model shows that it seems like the only variable that is significant in a linear regression model for predicting patient no-shows is hypertension.The R-squared is very low though, however, so this means that there must be other variables that we can look at for a better fit.")
```

```{r}
lmModelCharacteristics <- lm(No.show ~ Gender + Age + Scholarship, data = docapt)
summary(lmModelCharacteristics)

cat("This linear regression model shows that Age and Scholarship are more significant in determining the probability of a patient no show, although the R-squared is still very low like before.")
```

```{r}
docapt$waitingTime <- as.integer(docapt$waitingTime)

lmModelTime <- lm(No.show ~ AppointmentDay + fullScheduledDate + fullScheduledTime + hourOfSchedule + weekday + month + appointmentMonth + waitingTime, data = docapt)
summary(lmModelTime)

cat("This linear regression model shows that the day and month of appointment, day and month of scheduling the appointment, and amount of time waited between the scheduled day and appointment day are significant. However, like the previous linear regression models, the R-squared is very low.")
```

```{r}
lmOptimal <- lm(No.show ~ Age + Scholarship + AppointmentDay + fullScheduledDate + month + appointmentMonth + waitingTime, data = docapt)
summary(lmOptimal)

cat("This 'optimal' linear regression model includes only the variables that were significant in the previous models. However, the R-squared is still very low, which ultimately means that linear regression models are probably not the best to use to predict no-shows.")
```


```{r}
glmOptimal <- glm(No.show ~ Age + Scholarship + AppointmentDay + fullScheduledDate + month + appointmentMonth + waitingTime + hourOfSchedule, data = docapt)
summary(glmOptimal)

cat("This generalized linear regression model includes all variables that were significant, but because the values for null deviance, residual deviance, and AIC are very high, we don't think this would be the best model for predicting no shows either. However, when we were testing other variables, this mix of variables turned out to be the lowest generated AIC, and all the variables are significant.")
```

```{r}
probit.model <- glm(No.show ~ Age + Scholarship + AppointmentDay + fullScheduledDate + month + appointmentMonth + waitingTime + hourOfSchedule, data = docapt, family = binomial(link="probit"))
summary(probit.model)

cat("The probit model for the above variables also has very high values for null deviance, residual deviance, and AIC. Ultimately, linear regression and logistic regression models probably aren't the best model for predicting patient no shows.")
```

Scholarship Analysis
```{r}
counts5= table(docapt$No.show, docapt$Scholarship)
barplot(counts5, main="Appointment Data by Scholarship", beside=TRUE, names.arg = c("No Scholarship", "Scholarship"), legend = c("No Show", "Show"), xlab = "Scholarship", ylab= "Number of People", col = c("Green","Blue"))

noScholProp <- length(which(docapt$Scholarship == 0 & docapt$No.show == 0)) / (length(which(docapt$Scholarship == 0 & docapt$No.show == 0)) + length(which(docapt$Scholarship == 0 & docapt$No.show == 1)))

hasScholProp <- length(which(docapt$Scholarship == 1 & docapt$No.show == 0)) / (length(which(docapt$Scholarship == 1 & docapt$No.show == 0)) + length(which(docapt$Scholarship == 1 & docapt$No.show == 1)))

cat("The proportion of no shows amongst patients who have Scholarship is", hasScholProp, ", and the proportion of no shows amongst patients who did not have Scholarship is", noScholProp, ". This is interesting because patients who have Scholarship are those who receive financial aid from the Bolsa Familia and are generally worse off compared to those who don't have Scholarship, and we wish there was more data for us to pull from to dive into why those who are receiving aid are not showing up to their doctor appointments (which are probably subsidized in some form by the aid) as much as those who are not receiving aid.")
```

